[project]
name = "logs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.3",
    "numpy>=2.1.2",
    "sqlmodel>=0.0.22",
]
